name: Run Azure Login 
on: [push]
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: Login to Aaure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          
