name: Run Azure Login 
on:
  push:
    branches:
      - main
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: Login to Azure
          uses: Azure/login@v1.4.6
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS}}
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
            
            
          
